### ISSUE TITLE
Better handling of corner cases

### ISSUE THREAD

**Issue by BoAi01** [AY2223S2-CS2103T-W11-1/tp#110]
Error handling will be very important to tackle our PE. 
In our current product, there are many corner cases that our program may not handle well, such as
* the user links a crew to a plane that is at a different location
* the user changes a crew's location while it is already linked to a flight with a different start location

We probably need to consider how the program is expected to respond to such cases.

**Comment by cetigerlily** [comment]
> Error handling will be very important to tackle our PE. In our current product, there are many corner cases that our program may not handle well, such as
> 
> * the user links a crew to a plane that is at a different location
> * the user changes a crew's location while it is already linked to a flight with a different start location
> 
> We probably need to consider how the program is expected to respond to such cases.

I would guess we can create more exceptions that deal with these corner cases? We could also add a step during the linking process whereby we check the location of the object to be linked, and the location of the flight we want to link it to - if they're in different locations, we could indicate that message.

**Comment by BoAi01** [comment]
Need to ensure the following:

1. When flight-related sources (crew, pilot, plane) are linked to flights, they cannot be re-linked to 
a. new flights
b. new locations 
To achieve this, we can add a variable on these objects `isLocked`, set to true when they are linked to flights. 

2. When flights are marked as done, the linked resources are unlocked, i.e., they can be re-linked to new flights or new locations. This means `isLocked = false`. 

3. When location-related sources (crew, pilot, plane) are linked to locations, they cannot be relocated to new locations. Thus, if the user wants to relocate, e.g., a plane, then the plane must be unlinked first. This can be achieved with another boolean `isLocationLocked`. 
But how does the user know where the plane is linked to, given that it is not displayed on GUI? A quick fix would be to save the name string of the location as an attribute of the plane, then the user has to figure out the index of the location to un-link it.  However, if this is the case, we must ensure that there are no two locations with the same name. 

4. What if the user unlinks a resource from flight/location that it is actually not linked to? The current program does not seem to do anything about it. To check this, we can verify whether the flight/location name stored as the attribute of the resource is the same as the name of the flight/location corresponding to the user-input index. 

If we implement it this way, then the name string actually becomes the unique identifier of an object.

**Comment by BoAi01** [comment]
The solution is to change our product specification as following:

`link A B` means there is a relation between A and B. If a plane is linked to many places, it means the plane *might* stay in one of the places. If a plane is linked to many flights, it means the flight might use one of the planes for travel. The same for crews, pilots, etc. 

And we dont enfore that all flight-related resources should stay in one place since they can move around.
