### ISSUE TITLE
UG edits based on CS2101 feedback

### ISSUE THREAD

**Issue by jishnu28** [AY2223S2-CS2103T-W11-1/tp#150]
Yuanyuan:
- [x] 1. Remove AB-3 heading
- [x] 2. Edit green-underline sentences throughout doc
- [x] 3. More reassuring tone for intro
- [x] 4. Simplify/Remove CLI and GUI definitions
- [x] 5. Add full list of features to contents table
- [x] 6. Improve UG navigability (e.g. by adding a 'back to contents' link after each section)
- [x] 7. Improve 'how to use' section
- [x] 8. Simplify instructions for 'getting started' or add links to more info about java, terminal, etc
- [x] 9. Cover all major OS in 'getting started'
- [ ] 10. label parts of GUI (2103 only required no annotations for the Ui.png file)

Jishnu:
- [x] 11. Rephrase linking to FAQ
- [x] 12. Give more guidance in front matters (e.g. navigating UG)
- [x] 13. Move the 'modal editing' section out to make it more prominent and state how it should be read first
- [x] 14. Add definitions for terms like prefix, resource, resource entity etc and link their first use to their definitions in glossary
- [x] 15. Use callouts for important notes (e.g. 'adding a resource' section)

Celeste:
- [x] 16. Explain options for crew and pilot ranks
- [x] 17.  Replace screenshots for new UI and better visibility (incl. annotations)
- [x] 18. Add screenshots for complex commands
- [x] 19. Look through 'input-output' code blocks 
- [x] 20. Clarify whether multiple resource entities can be linked/unlinked in one go
- [x] 21. Add a section about command formatting

**Comment by jishnu28** [comment]
The glossary table appears normally in the github preview but it doesn't display properly in the [user guide page](https://ay2223s2-cs2103t-w11-1.github.io/tp/UserGuide.html). Not sure why, perhaps there has to be an empty line between the header and the table itself

**Comment by cetigerlily** [comment]
Yes, I'll add them later when I've edited them!
