### ISSUE TITLE
[PE-D][Tester B] Crew Members can be duplicated

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#152]
![Screenshot 2023-03-31 at 3.02.12 PM.png](https://raw.githubusercontent.com/Oliverloo0909/ped/main/files/bc20d659-da26-4215-987a-c02749e891e6.png)

The allowance of crew members having the exact same field might cause confusion. As shown in the diagram above, an airline manager might mix up two people, on the off chance they have the same name and roles. Using a restriction to a unique list would help solve the issue.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Oliverloo0909/ped#1

**Comment by BoAi01** [comment]
Done. Now crews should have different names.

**Comment by wxxedu** [comment]
I disagree. It would be rude not to allow people with same names.
