### ISSUE TITLE
[PE-D][Tester D] Outdated Download Link in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#154]
The hyper link in the `Getting Started` section in the User Guide is fixed to your v1.3 release, which is already outdated during the PE-Dry run.
Can change the link into "https://github.com/AY2223S2-CS2103T-W11-1/tp/releases" so that the latest release are shown.

![Outdated_release_link.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/9078d095-a809-4941-aab4-34fe10501fa0.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: chen-jerry-junior/ped#1

**Comment by BoAi01** [comment]
Good suggestion. Leave it to documentation.
