### ISSUE TITLE
[PE-D][Tester A] Extra semicolon at the end of the sentence for `Deleting a resource`

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#157]
![Screenshot 2023-03-31 at 2.24.08 PM.png](https://raw.githubusercontent.com/Merrickneo/ped/main/files/2689e1cf-df8f-4cb3-8a6f-6d9e3649312d.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Merrickneo/ped#4

**Comment by BoAi01** [comment]
inavlid
