### ISSUE TITLE
[PE-D][Tester F] Program uses one-indexing but User Guide uses zero-indexing

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#162]
The program's arguments and internal help messages are one-indexed.
However, the command explanations & examples of the User Guide are zero-indexed.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jefrai/ped#2

**Comment by BoAi01** [comment]
Need to update UG.

**Comment by jishnu28** [comment]
UG has been updated to no longer mention 0-indexing.
