### ISSUE TITLE
[PE-D][Tester A] Linking flights and locations

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#173]
If I am linking a flight and location together, I would expect the particular location to be also display the link to the particular flight.

Currently, the link is not there.

![Screenshot 2023-03-31 at 2.44.28 PM.png](https://raw.githubusercontent.com/Merrickneo/ped/main/files/c76486f0-c538-44e9-84b7-fabb4d27a9b7.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Merrickneo/ped#8

**Comment by BoAi01** [comment]
Probably we should make it clear in UG that we want to avoid duplicate information.
