### ISSUE TITLE
[PE-D][Tester F] The exit command is non-functional.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#174]
Steps:

1. Enter `exit`.

Actual:

The program responds with `Unknown command in [mode]`

Expected:

The program exits.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jefrai/ped#4

**Comment by BoAi01** [comment]
Done. Have added `exit` command.
