### ISSUE TITLE
[PE-D][Tester F] Entering an invalid gender for a pilot elicits no response from the program.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#178]
Steps:

1. In pilot mode, enter e.g. `add /n pname /r 1 /a 1 /g 4 /fh 1`

Actual:

The program provides no response.

Expected:

An error message explaining the invalid gender should be written to screen.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jefrai/ped#5

**Comment by BoAi01** [comment]
Added input value check for gender and pilot rank.
