### ISSUE TITLE
[PE-D][Tester D] Unaligned Feature Description in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#182]
According to the user guide, when changing the mode, the UI will show two list. However, in the actual product, after changing the mode, the UI doesn't display any changes except the current mode name.
![Unaligned_Feature_Description.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/6832561f-6a0e-45cd-ab05-4bb8af635457.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: chen-jerry-junior/ped#6

**Comment by cetigerlily** [comment]
We've fixed this problem in the UG with an updated description!
