### ISSUE TITLE
[PE-D][Tester B] Integer values allowed in crew name 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#185]
![Screenshot 2023-03-31 at 2.59.09 PM.png](https://raw.githubusercontent.com/Oliverloo0909/ped/main/files/7ccd46ac-b089-4159-b0f2-7041abd42f36.png)

name usually will never contained only integers, hence this should throw an error message. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Oliverloo0909/ped#8

**Comment by BoAi01** [comment]
Not quite an issue.
