### ISSUE TITLE
[PE-D][Tester D] Unusable Scroll Bar

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#188]
The Scroll Bar under the mode shows that there is more space towards the right. However, the scroll bar cannot be moved, which is a little misleading.

![Malfunctioning_Scroll_Bar.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/51a1939a-1874-441a-b079-f77bb45b5d31.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: chen-jerry-junior/ped#8

**Comment by BoAi01** [comment]
Invalid
