### ISSUE TITLE
[PE-D][Tester B] No error message nor success message when delete 0 is entered 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#191]
![Screenshot 2023-03-31 at 3.10.03 PM.png](https://raw.githubusercontent.com/Oliverloo0909/ped/main/files/14122733-4064-42eb-a8b8-4243dcc035e2.png)

delete 0 likely throws an invocation target exception. as the program is not responsive. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Oliverloo0909/ped#10

**Comment by cetigerlily** [comment]
I think 'delete 0' does actually throw the proper error message and I've tested this successfully across all modes - so this is an invalid issue and I'll close this now. 

<img width="306" alt="Screenshot 2023-04-06 at 10 26 07" src="https://user-images.githubusercontent.com/92414500/230256782-85209c9c-8275-47ca-ae5d-5c5119f8c199.png">
