### ISSUE TITLE
[PE-D][Tester D] Out of Bound Index Unchecked

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#192]
While Linking a flight to a location, the /from and /to input didn't check where the index is out of bound. The image below is the UI after input `linklocation /fl 2 /from 1 /to 3`, under the case that there is only one location in prescence.
![Out_of_Bound_Index_Unchekced.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/5e37cc41-8085-430b-bd15-980c95f8a430.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: chen-jerry-junior/ped#9

**Comment by BoAi01** [comment]
Solved. Added check to ensure the input two locations are valid, before performing link operation.
