### ISSUE TITLE
[PE-D][Tester C] A command that's not supposed to work is working for some reason

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#204]
this command is working for some reason

![image.png](https://raw.githubusercontent.com/Saha9616/ped/main/files/c1020b40-4bd7-422d-81dd-c7fdc6ea9f0a.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Saha9616/ped#5

**Comment by BoAi01** [comment]
the command no longer exists. also, have added check for empty string values.
