### ISSUE TITLE
[PE-D][Tester C] Able to add 2 flights with same code

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#205]
Able to add 2 flights with same code, airlines have different codes for different flights.

![image.png](https://raw.githubusercontent.com/Saha9616/ped/main/files/26d5c247-20cc-4710-8a55-666335dc96e2.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Saha9616/ped#6

**Comment by BoAi01** [comment]
Done.
