### ISSUE TITLE
[PE-D][Tester C] Unable to unlink csd(cabin service director) from flight even though it is present. Continuation of previous bug.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#207]
Step 1) first link a csd crew with slf command (previous bug) to  a flight

step 2) try to unlink the csd with a csd command

![image.png](https://raw.githubusercontent.com/Saha9616/ped/main/files/99590c53-1b1f-4b58-8b79-79645914adbd.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Saha9616/ped#8

**Comment by jishnu28** [comment]
The fix for this is to rename the ranks to not clash with the flightpositions for crew members AND 

also to display flightposition instead of rank for the crew in the flight panel since the link/unlink command rely on flightposition and not rank

**Comment by jishnu28** [comment]
Fixed with #235
