### ISSUE TITLE
[PE-D][Tester D] Repeatitive Link to Location

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#209]
A single resource can be linked to multipul locations, for example a plane can be linked to both Singapore and Shanghai. It might be better to restrict the limit of the number of links for each resource.

![Repeatitive-Link.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/ff68710e-1394-4e3e-a724-b1461298ed41.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: chen-jerry-junior/ped#10

**Comment by BoAi01** [comment]
Shift the link between locations and objects from the location class to the object classes.

**Comment by wxxedu** [comment]
Will update the doc and list it there

**Comment by jishnu28** [comment]
ADdressed in DG
