### ISSUE TITLE
[PE-D][Tester D] UG header for commands not clearly distinguishable

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#212]
Specifically speaking, you have detailed command explaination for each mode under every behavioral feature. But the header for the feature and the breakdown have no difference in size or color. A user might find himself/herself confused when looking through to guide.

![Header.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/1adbd611-64d5-4123-8576-a1909eb4ceda.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: chen-jerry-junior/ped#12

**Comment by jishnu28** [comment]
Changed the subheadings including mode from heading level 5 to heading level 6. Hopefully, that makes the difference clearer. The feature heading remains at level 4.
