### ISSUE TITLE
[PE-D][Tester E] Help window is not updated with correct link to UG 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#218]
Help window is still pointing to AddressBook UG (maybe you should change the link to your UG instead)

![image.png](https://raw.githubusercontent.com/dohaduong/ped/main/files/5139d304-8d2d-457f-8f29-53575cbcac60.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: dohaduong/ped#10

**Comment by BoAi01** [comment]
Fixed. PR coming soon.
