### ISSUE TITLE
[PE-D][Tester D] Misleading UI infomation

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#219]
When linking a crew to a flight, you need to assign the rank that the crew is linked to, but this assigned rank is not shown in the crew section under flight. A user is likely to mix up the assigned rank with the original rank of the crew. Thus when executing `unlinkflight`, it is hard for the user to remember what the assigned rank is.

The image below shows a crew of rank Flight Attendants assigned to flight 1 as a csd. When executing `unlinkflight`, it's easy to misremember that this crew is assigned as a Flight Attendants.

It might be better to show the assigned rank under the flight information instead of the original rank of the crew.

![Unmatch_link.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/8c1d6db9-89b3-4bc6-aa6c-9f3c094b7367.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: chen-jerry-junior/ped#15

**Comment by BoAi01** [comment]
Summary of the issue: A senior flight attendant could be assigned as the Cabin Service Director of a flight. There is a mismatch here. 

<img width="1044" alt="Screenshot 2023-04-01 at 11 59 49 AM" src="https://user-images.githubusercontent.com/53465243/229264633-ad5531a4-a018-4a7e-a4b6-531d821162e8.png">
