### ISSUE TITLE
[PE-D][Tester D] Find or Filter command needed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#221]
After a user created a lot of resources and saved it in the product, it's hard to remember the index of each resource and it'll be tired to search through the list one by one using the scroll bar. A find command might be helpful so that as long as the user remember any infomation about the resource, he/she can have access to it very quickly.

![Find_Command_Needed.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/d1ee041d-d252-4242-b0c5-31bf3c2372a4.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: chen-jerry-junior/ped#17

**Comment by wxxedu** [comment]
I doubt we can implement this in v1.4. I don't think that this feature is needed though.

**Comment by BoAi01** [comment]
Let's no close issues at the moment, as we still need to grade the testers on their comments.

**Comment by BoAi01** [comment]
No adding feature allowed. Invalid suggestion.
