### ISSUE TITLE
Support duplicated prefixes in the parsing logic

### ISSUE THREAD

**Issue by wxxedu** [AY2223S2-CS2103T-W11-1/tp#46]
Currently duplicated prefixes would not result in any warning, and it would not be reflected in the data structure (the latter one would simply override the former one).

For example, say the keyword is `\n`:

```
add \n something \n something2
```
Then `something2` would replace `something`. 

We have two choices:
1. support parsing of duplicated prefixes
2. throw a `ParseException` if such duplication does occur.

**Comment by BoAi01** [comment]
interesting.. an easy fix would be to detect duplicate prefixes in the parsed argument list

I would prefer 2.

**Comment by wxxedu** [comment]
2 is a really good option if we don't plan to support duplicate info, and it's easier to implement as well.

**Comment by cetigerlily** [comment]
I could only figure out how to do this for commands in this form:
`commandType /prefix1 xxx /prefix2 xxx`

when /prefix1 is typed more than once. However, it doesn't detect an error when /prefix2 is typed more than once. Similarily, for commands which only take one prefix, I also wasn't able to have the parser detect the issue...

**Comment by BoAi01** [comment]
I believe this has been done?

**Comment by wxxedu** [comment]
Not yet, I am working on it

**Comment by wxxedu** [comment]
Should be fixed with PR #236
