### ISSUE TITLE
Fix the revolving behavior for `crew`

### ISSUE THREAD

**Issue by wxxedu** [AY2223S2-CS2103T-W11-1/tp#93]
As what I have pointed out in #91, I think it may be better if we could choose not to use `putRevolve` in adding a crew's link to the flight, because it may not make logical sense.

**Comment by wxxedu** [comment]
Similar issues for other link commands should also be investigated.

**Comment by jishnu28** [comment]
Replace putrevolve with just put and let the shape handle the case where number of crew being added exceeds the number of crew specified in shape
